=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="layout">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice maxOccurs="unbounded">
		    		<xsd:element name="field" type="fieldType" minOccurs="0" maxOccurs="unbounded"/>
		    		<xsd:element name="list" type="listType" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="desc" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="fieldType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="name" type="xsd:string" use="required"/>
				<xsd:attribute name="maxBytes" type="xsd:int" use="required"/>
				<xsd:attribute name="required" default="N">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="Y"/>
							<xsd:enumeration value="N"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="type" use="required">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="C"/>
							<xsd:enumeration value="N"/>
							<xsd:enumeration value="D"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="desc" type="xsd:string"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="listType">
		<xsd:sequence>
    		<xsd:element name="field" type="fieldType" minOccurs="0" maxOccurs="unbounded"/>
    		<xsd:element name="list" type="listType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="minOccurs" type="xsd:int" use="required"/>
		<xsd:attribute name="maxOccurs" type="xsd:int" use="required"/>
		<xsd:attribute name="desc" type="xsd:string"/>
	</xsd:complexType>

</xsd:schema>

=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/0100-100-req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<layout desc="지급 이체 요청" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./layout.xsd">

	<field name="MESSAGECODE"	maxBytes="4"	required="Y"	type="C"	desc="메시지코드" />
	<field name="SERVICECODE"	maxBytes="3"	required="Y"	type="C"	desc="업무구분코드" />
	<field name="GRPBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="단지사업자번호" />
	<field name="MEMBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="상사사업자번호" />
	<field name="ISSUENO"		maxBytes="20"	required="Y"	type="C"	desc="거래고유번호" />
	
	<field name="OUTBANKCD"		maxBytes="3"	required="Y"	type="C"	desc="출금은행코드" />
	<field name="OUTACCTNO"		maxBytes="15"	required="Y"	type="C"	desc="출금계좌번호" />
	<field name="OUTACCTPW"		maxBytes="8"	required="N"	type="C"	desc="출금계좌비밀번호" />
	<field name="OUTAMT"		maxBytes="13"	required="Y"	type="C"	desc="출금금액" />
	<field name="OUTDESC"		maxBytes="20"	required="N"	type="C"	desc="출금계좌적요" />
	
	<field name="INBANKCD"		maxBytes="3"	required="Y"	type="C"	desc="입금은행코드" />
	<field name="INACCTNO"		maxBytes="15"	required="Y"	type="C"	desc="입금계좌번호" />
	<field name="INDESC"		maxBytes="20"	required="Y"	type="C"	desc="입금계좌적요" />
	
	<field name="CMSCD"			maxBytes="16"	required="N"	type="C"	desc="CMS코드" />
	<field name="SALARYYN"		maxBytes="1"	required="N"	type="C"	desc="급여구분" />
</layout>

=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/0600-400-req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<layout desc="예금주명 요청" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./layout.xsd">

	<field name="MESSAGECODE"	maxBytes="4"	required="Y"	type="C"	desc="메시지코드" />
	<field name="SERVICECODE"	maxBytes="3"	required="Y"	type="C"	desc="업무구분코드" />
	<field name="GRPBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="단지사업자번호" />
	<field name="MEMBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="상사사업자번호" />
	<field name="ISSUENO"		maxBytes="20"	required="Y"	type="C"	desc="거래고유번호" />
	<field name="TRXDAT"		maxBytes="4"	required="Y"	type="C"	desc="거래일자(MMDD)" />
	<field name="BANKCD"		maxBytes="3"	required="Y"	type="C"	desc="조회대상은행코드" />
	<field name="ACCTNO"		maxBytes="16"	required="Y"	type="C"	desc="조회대상계좌번호" />
	<field name="TRXAMT"		maxBytes="13"	required="N"	type="C"	desc="거래금액" />
</layout>

=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/0600-300-req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<layout desc="잔액 조회 요청" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./layout.xsd">

	<field name="MESSAGECODE"	maxBytes="4"	required="Y"	type="C"	desc="메시지코드" />
	<field name="SERVICECODE"	maxBytes="3"	required="Y"	type="C"	desc="업무구분코드" />
	<field name="GRPBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="단지사업자번호" />
	<field name="MEMBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="상사사업자번호" />
	<field name="ISSUENO"		maxBytes="20"	required="Y"	type="C"	desc="거래고유번호" />
	<field name="BANKCD"		maxBytes="3"	required="Y"	type="C"	desc="조회대상은행코드" />
	<field name="ACCTNO"		maxBytes="15"	required="Y"	type="C"	desc="조회대상계좌번호" />
</layout>

=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/9999-002-req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<layout desc="상사 사업자정보 등록" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./layout.xsd">

	<field name="MESSAGECODE"	maxBytes="4"	required="Y"	type="C"	desc="메시지코드" />
	<field name="SERVICECODE"	maxBytes="3"	required="Y"	type="C"	desc="업무구분코드" />
	<field name="GRPBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="단지사업자번호" />
	<field name="MEMBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="상사사업자번호" />
	<field name="MEMNM"			maxBytes="100"	required="Y"	type="C"	desc="상사사업자명" />
	<field name="CHANNEL"		maxBytes="30"	required="Y"	type="C"	desc="전용선 업체코드" />
	<field name="BANKCD"		maxBytes="3"	required="Y"	type="C"	desc="은행코드" />
	<field name="FBSCODE"		maxBytes="8"	required="Y"	type="C"	desc="FBS업체코드" />
	<field name="RECCODEYN"		maxBytes="1"	required="Y"	type="C"	desc="복기부호 사용여부" />
</layout>

=== suhojang/RESTfulAPIforBank/src/main/webapp/WEB-INF/layout/0200-300-req.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<layout desc="거래내역조회 요청" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./layout.xsd">

	<field name="MESSAGECODE"	maxBytes="4"	required="Y"	type="C"	desc="메시지코드" />
	<field name="SERVICECODE"	maxBytes="3"	required="Y"	type="C"	desc="업무구분코드" />
	<field name="GRPBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="단지사업자번호" />
	<field name="MEMBIZNO"		maxBytes="13"	required="Y"	type="C"	desc="상사사업자번호" />
	<field name="ISSUENO"		maxBytes="20"	required="Y"	type="C"	desc="거래고유번호" />
	<field name="BANKCD"		maxBytes="3"	required="Y"	type="C"	desc="조회은행코드" />
	<field name="CURRCD"		maxBytes="3"	required="Y"	type="C"	desc="조회통화코드" />
	<field name="ACCTNO"		maxBytes="15"	required="N"	type="C"	desc="조회계좌번호" />
	<field name="SDATE"			maxBytes="8"	required="Y"	type="C"	desc="조회시작일자" />
	<field name="EDATE"			maxBytes="8"	required="Y"	type="C"	desc="조회종료일자" />
	<field name="CURRPAGENO"	maxBytes="5"	required="Y"	type="C"	desc="요청페이지" />
</layout>
